### ISSUE TITLE
Listener doesn't start

### ISSUE THREAD

**Issue by astronode** [robcowart/synesis_lite_syslog#6]
Hi Rob, followed the instructions but the 514 port listener fails to start for some reason -

`[2019-05-15T12:05:05,250][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:514", :ssl_enable=>"false"}
[2019-05-15T12:05:05,256][ERROR][logstash.javapipeline    ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:synesis_lite_syslog
  Plugin: <LogStash::Inputs::Tcp host=>"0.0.0.0", dns_reverse_lookup_enabled=>false, id=>"dbb44d7e7b498a36341cfa76571b5c366d668ed2b496086bcc69ec34add2adb2", type=>"syslog", port=>514, enable_metric=>true, codec=><LogStash::Codecs::Line id=>"line_ed18c78c-5642-4b13-9fc6-67f140d700c5", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, mode=>"server", proxy_protocol=>false, ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>, tcp_keep_alive=>false>
  Error: Permission denied
  Exception: Java::JavaNet::SocketException
  Stack: sun.nio.ch.Net.bind0(Native Method)
sun.nio.ch.Net.bind(sun/nio/ch/Net.java:461)
sun.nio.ch.Net.bind(sun/nio/ch/Net.java:453)
sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:227)
io.netty.channel.socket.nio.NioServerSocketChannel.doBind(io/netty/channel/socket/nio/NioServerSocketChannel.java:128)
io.netty.channel.AbstractChannel$AbstractUnsafe.bind(io/netty/channel/AbstractChannel.java:558)
io.netty.channel.DefaultChannelPipeline$HeadContext.bind(io/netty/channel/DefaultChannelPipeline.java:1283)
io.netty.channel.AbstractChannelHandlerContext.invokeBind(io/netty/channel/AbstractChannelHandlerContext.java:501)
io.netty.channel.AbstractChannelHandlerContext.bind(io/netty/channel/AbstractChannelHandlerContext.java:486)
io.netty.channel.DefaultChannelPipeline.bind(io/netty/channel/DefaultChannelPipeline.java:989)
io.netty.channel.AbstractChannel.bind(io/netty/channel/AbstractChannel.java:254)
io.netty.bootstrap.AbstractBootstrap$2.run(io/netty/bootstrap/AbstractBootstrap.java:364)
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(io/netty/util/concurrent/AbstractEventExecutor.java:163)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(io/netty/util/concurrent/SingleThreadEventExecutor.java:403)
io.netty.channel.nio.NioEventLoop.run(io/netty/channel/nio/NioEventLoop.java:463)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(io/netty/util/concurrent/SingleThreadEventExecutor.java:858)
io.netty.util.concurrent.FastThreadLocalRunnable.run(io/netty/util/concurrent/FastThreadLocalRunnable.java:30)
java.lang.Thread.run(java/lang/Thread.java:834)`

**Comment by Rajikoro** [comment]
confirm, experiencing a similar problem

@robcowart

**Comment by Rajikoro** [comment]
The fact is that the machine already has a syslog listening on this port. If you change the port, then everything is ok.

**Comment by Rajikoro** [comment]
fix: `sysctl net.ipv4.ip_unprivileged_port_start=0`

https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by astronode** [comment]
Can be circumvented by creating a firewalld port forward:
```
sudo firewall-cmd --add-forward-port=port=514:proto=udp:toport=5514 --permanent
sudo firewall-cmd --add-forward-port=port=514:proto=tcp:toport=5514 --permanent
```
